### ISSUE TITLE
Question: Widget template?

### ISSUE THREAD

**Issue by NicolasGoerlach** [codefog/contao-polls#10]
Hey dude, nice extension - thanks for providing it!
Where I can find the template that is loaded for creating the checkbox or radio widget in html?
I've overwrited the default contao form_checkbox and form_radio html templates and I want to use them in your extension, how is that possible?

**Comment by qzminski** [comment]
There is no special template here, so that should work. Are you sure they are in correct templates folder? What's your Contao version?

**Comment by NicolasGoerlach** [comment]
Hm, yes they are in the template directory and they are already working in my contact form. Im using Contao 3.5.30. Another information: Your extension didnt set the correct widget classes, if I choice "Type => Multiple vote (checkbox)" the class should be "widget widget-checkbox".

**Comment by qzminski** [comment]
Please try to adjust the poll template by changing this line https://github.com/codefog/contao-polls/blob/master/templates/poll_default.html5#L28 into `<?php echo $this->options->parse(); ?>`.

**Comment by NicolasGoerlach** [comment]
Works, but I get a lot of breaks between the REQUEST_TOKEN field and the fieldset, any ideas?
![bildschirmfoto 2017-11-14 um 11 58 53](https://user-images.githubusercontent.com/8327905/32776555-39ecb6ce-c933-11e7-8d6a-a2cfc5ac3876.jpg)

**Comment by qzminski** [comment]
Don't you get the same white spaces in your contact form? At first sight it looks like this code is coming from your custom template.

**Comment by NicolasGoerlach** [comment]
Nope, didnt get it anywhere else - same issue if I use the contao standard template for my checkboxes.

**Comment by qzminski** [comment]
No idea to be honest 🙈

**Comment by NicolasGoerlach** [comment]
Seems to be my fault, I modified the poll_default a bit! 
Ticket can be closed, but I think you should publish the adjustment!
Thanks for help
