### ISSUE TITLE
Invalid request token

### ISSUE THREAD

**Issue by derastronaut** [codefog/contao-polls#12]
Hello Kamil,

some of my users reported me that they get an "invalid request token" when they visit a page with a poll. I attached a screenshot of the contao-error-site but it's in German. The contao-logs are empty.

The affected website uses Contao 4.5.6 with Polls 1.5.0.

![contao-poll](https://user-images.githubusercontent.com/5235594/37244153-f1b53a72-2484-11e8-9c1b-b0be38055b6e.jpg)

**Comment by qzminski** [comment]
Are you using the default template? Can you check if the below line is present in the source code of your page?

https://github.com/codefog/contao-polls/blob/master/templates/poll_default.html5#L26

**Comment by derastronaut** [comment]
Yes, the line is there.

I modified the template a bit. I tried to post the complete template here but it seems not to be allowed because some tags are being deleted. So I loaded up the file in my cloud: cloud.derastronaut.de/index.php/s/jdqyjYJnWkitZFN

**Comment by qzminski** [comment]
The template looks good. Does this error occur only after you submit the poll form? Or when you immediately enter the page maybe?

**Comment by derastronaut** [comment]
The error occurs immediately when navigating to the page where the poll is. Users reported that this occurs after they clicked on my shared link in Facebook but also when they navigated from the startpage or other subpages to the news with the poll. BTW: I integrated the poll into a news: handballforum-dormagen.de/news/umfrage-auf-welchem-tabellenplatz-siehst-du-den-tsv-am-saisonende-2017-18
But the poll is closed now.

**Comment by qzminski** [comment]
In that case there must probably be some sort of POST request going on and I think it's not related to the poll extension. This error comes up when you make a POST request and do not include the request token generated by Contao. I assume you tried disabling the poll element temporarily to see if error still appears?
