### ISSUE TITLE
Check IP-Address to prevent multiple votes

### ISSUE THREAD

**Issue by minstyle** [codefog/contao-polls#14]
Hi,

The following scenario:

I have a lot of contao members with all the same user/login data for the member area.

Each user is allowed to participate in the survey and cast a vote.

Is it possible to check the IP address of each user to limit the vote?

![image](https://user-images.githubusercontent.com/2649562/49025495-1d166800-f19c-11e8-8ad9-72a6732cb00f.png)

If I see this correctly, the extension only checkes if this is a registered user.

**Comment by qzminski** [comment]
If you disable this option, only the IP address will be used for validation (apart from cookie obviously): https://github.com/codefog/contao-polls/blob/master/classes/Poll.php#L260-L271

IMO your concept in general is bad by design, though. Not sure if this solution will work out for you.

**Comment by minstyle** [comment]
Thanks für your answer.

I know, it‘s a bad design concept. But the customer wants it.
