### ISSUE TITLE
update default CSS classes to Contao standard

### ISSUE THREAD

**Issue by frontendschlampe** [codefog/contao-polls#15]
Currently you use the "old" CSS-classes for the widgets. It would be great to update them to the current standard.

For example:
checkbox container ```widget``` --> ```widget widget-checkbox```
Submit container ```submit_container``` --> ```widget widget-submit```

Thank you.

**Comment by qzminski** [comment]
I think if I replace `submit_container` completely it could break the existing setups. Thus I will just add the missing classes as extra stuff.
